// components
export { couponDataSource } from './Coupon/data';
export { goodsGridDataSource, tabGoodsDataSource } from './GoodsGrid/data';
export { goodsThreeDataSource } from './GoodsThree/data';
export { gridDataSource } from './Grid/data';
export { inputDataSource } from './Input/data';
export { videoDataSource } from './Video/data';
export { audioDataSource } from './Audio/data';
export { searchBarDataSource } from './SearchBar/data';
export { titlelineDataSource } from './Titleline/data';
export { titleDataSource, subTitleDataSource } from './Title/data';
export { textareaDataSource } from './Textarea/data';
export { swiperDataSource } from './Swiper/data';
export { spacelineDataSource } from './SpaceLine/data';
export { tabBarDataSource } from './TabBar/data';
export { tabsDataSource } from './Tabs/data';
export { htmlPageDataSource } from './Html/data';
export { imageDataSource, imageListDataSource } from './Image/data';
export { containerDataSource } from './Container/data';
export { mapDataSource } from './Map/data';
export { cartBuyDataSource } from './CartBuy/data';
export { cartAddDataSource } from './CartAdd/data';
export { cartGoodDataSource } from './CartGood/data';
export { buttonDataSource } from './Button/data';
export { listDataSource } from './List/data';
export { imagePickerDataSource } from './ImagePicker/data';
export { loginAvatarDataSource } from './LoginAvatar/data';
export { noticebarDataSource } from './Noticebar/data';
export { contactDataSource } from './Contact/data';
export { locationSwitchDataSource } from './LocationSwitch/data';
export { loadMoreDataSource } from './LoadMore/data';
export { cartListDataSource } from './CartList/data';
export { goodSkuDataSource } from './GoodSku/data';
export { pDataSource } from './Article/data';
export { infoDataSource } from './Article/data';
export { imgDataSource } from './Article/data';
export { shopItemDataSource } from './Shop/data';
export { shopListDataSource } from './Shop/data';
// export { playVioceDataSource } from './Voice/data';
export { wechatLoginDataSource } from './Wechat/data';
